osx_image: xcode11.6
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

before_install:
  - echo "$TRAVIS_BUILD_DIR"


script:
  - set -o pipefail
  - xcodebuild -workspace Growing/Example/GrowingIO.xcworkspace -scheme GrowingAutoTracker -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c


script:
    - echo "hello world"
