osx_image: xcode11.6
language: objective-c

script:
    - set -o pipefail && xcodebuild -project Growing/Example/GrowingIO.xcworkspace -scheme GrowingAutoTracker -sdk
    iphoneos -configuration Release | xcpretty
