osx_image: xcode11.6
language: objective-c


xcode_workspace: ./Growing/Example/GrowingIO.xcworkspace # path to your xcodeproj folder
xcode_scheme: GrowingAutoTracker
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

script:
    - echo "hello world"
